[python]
label = "Python"

    [[python.questions]]
    question     = "When was the first known use of the word 'quiz'"
    answers      = ["1781"]
    alternatives = ["1771", "1871", "1881"]

    [[python.questions]]
    question     = "Which built-in function can get information from the user"
    answers      = ["input"]
    alternatives = ["get", "print", "write"]

    [[python.questions]]
    question = "What's the purpose of the built-in zip() function"
    answers = ["To iterate over two or more sequences at the same time"]
    alternatives = [
        "To combine several strings into one",
        "To compress several files into one archive",
        "To get information from the user",
    ]

    [[python.questions]]
    question     = "What does dict.get(key) return if key isn't found in dict"
    answers      = ["None"]
    alternatives = ["key", "True", "False"]

    [[python.questions]]
    question = "How do you iterate over both the indices and elements in an iterable"
    answers = ["enumerate(iterable)"]
    alternatives = [
        "enumerate(iterable, start=1)",
        "range(iterable)",
        "range(iterable, start=1)",
    ]

    [[python.questions]]
    question = "What's the official name of the := operator"
    answers = ["Assignment expression"]
    alternatives = [
        "Named expression",
        "Walrus operator",
        "Colon equals operator",
    ]

    [[python.questions]]
    question = "What's one effect of calling random.seed(42)"
    answers = ["The random numbers are reproducible."]
    alternatives = [
        "The random numbers are more random.",
        "The computer clock is reset.",
        "The first random number is always 42.",
    ]

    [[python.questions]]
    question     = "Which version of Python is the first with TOML support built in"
    answers      = ["3.11"]
    alternatives = ["3.9", "3.10", "3.12"]

    [[python.questions]]
    question     = "How can you run a Python script named quiz.py"
    answers      = ["python quiz.py", "python -m quiz"]
    alternatives = ["python quiz", "python -m quiz.py"]
    hint         = "One option uses the filename, and the other uses the module name."

    [[python.questions]]
    question     = "What's the name of the list-like data structure in TOML"
    answers      = ["Array"]
    alternatives = ["List", "Sequence", "Set"]

    [[python.questions]]
    question = "What's a PEP"
    answers = ["A Python Enhancement Proposal"]
    alternatives = [
        "A Pretty Exciting Policy",
        "A Preciously Evolved Python",
        "A Potentially Epic Prize",
    ]
    hint = "PEPs are used to evolve Python."
    explanation = """
    Python Enhancement Proposals (PEPs) are design documents that provide
    information to the Python community. PEPs are used to propose new features
    for the Python language, to collect community input on an issue, and to
    document design decisions made about the language.
    """

    [[python.questions]]
    question = "How can you add a docstring to a function"
    answers = [
        "By writing a string literal as the first statement in the function",
        "By assigning a string to the function's .__doc__ attribute",
    ]
    alternatives = [
        "By using the built-in @docstring decorator",
        "By returning a string from the function",
    ]
    hint = "They are parsed from your code and stored on the function object."
    explanation = """
    Docstrings document functions and other Python objects. A docstring is a
    string literal that occurs as the first statement in a module, function,
    class, or method definition. Such a docstring becomes the .__doc__ special
    attribute of that object. See PEP 257 for more information.
    There's no built-in @docstring decorator. Many functions naturally return
    strings. Such a feature can therefore not be used for docstrings.
    """

    [[python.questions]]
    question = "When was the first public version of Python released"
    answers = ["February 1991"]
    alternatives = ["January 1994", "October 2000", "December 2008"]
    hint = "The first public version was labeled version 0.9.0."
    explanation = """
    Guido van Rossum started work on Python in December 1989. He posted
    Python v0.9.0 to the alt.sources newsgroup in February 1991. Python
    reached version 1.0.0 in January 1994. The next major versions,
    Python 2.0 and Python 3.0, were released in October 2000 and December
    2008, respectively.
    """

[capitals]
label = "Capitals"

    [[capitals.questions]]
    question = "What's the capital of Norway"
    answers = ["Oslo"]
    hint = "Lars Onsager, Jens Stoltenberg, Trygve Lie, and Børge Ousland."
    alternatives = ["Stockholm", "Copenhagen", "Helsinki", "Reykjavik"]
    explanation = """
    Oslo was founded as a city in the 11th century and established as a
    trading place. It became the capital of Norway in 1299. The city was
    destroyed by a fire in 1624 and rebuilt as Christiania, named in honor
    of the reigning king. The city was renamed back to Oslo in 1925.
    """

    [[capitals.questions]]
    question = "What's the state capital of Texas, USA"
    answers = ["Austin"]
    alternatives = ["Harrisburg", "Houston", "Galveston", "Columbia"]
    hint = "SciPy is held there each year."
    explanation = """
    Austin is named in honor of Stephen F. Austin. It was purpose-built to
    be the capital of Texas and was incorporated in December 1839. Houston,
    Harrisburg, Columbia, and Galveston are all earlier capitals of Texas.
    """

    [[capitals.questions]]
    question = "what is the capital of Australia"
    answers = ["Canberra"]
    alternatives = ["Sydney", "Melbourne", "Perth", "Gold Coast"]
    hint = "has a NASA base"
    explanation = """
    The name Canberra is a derivation of an aboriginal term meaning "meeting place." 
    The city evolved frm a small squatters' settlement of stockmen which was there as easly as 1824,
    called Canberry or canbury. By 1836, the name had evolved to Canberra.
    """

    [[capitals.questions]]
    question = "what is the capital of Philippines"
    answers = ["Manila"]
    alternatives = ["Cebu", "Makati", "Quezon", "Caloocan"]
    hint = "there's a secret tunnel in the city"
    explanation = """
    The name manila came form a flower.It became the capital city of philippines because 
    Manila became the center of transportaion,commerce, culture and education.
    """

    [[capitals.questions]]
    question = "what is the capital of Thailand"
    answers = ["Bangkok"]
    alternatives = ["Chiang mai", "Phuket", "Thani", "Pattaya"]
    hint = "known as city of angels"
    explanation = """
    bangkok is a very popular asian city that people travel 
   to.Bangkok is also knows as the home of
   Redbull.
    """

    [[capitals.questions]]
    question = "what is the capital of South Korea"
    answers = ["Seoul"]
    alternatives = ["Busan", "Incheon", "Daegu", "Gwangju"]
    hint = "its the 3rd largest city in the world"
    explanation = """
    seoul is know for its vibrant districts, eclectic fashion scense,delicious street food, and being the the birthplace of Kpop. 
    """

    [[capitals.questions]]
    question = "what is the capital of China"
    answers = ["Beijing"]
    alternatives = ["Shanghai", "Wuhan", "Chengdu", "Shenzhen"]
    hint = "One of the Oldest cities in the world"
    explanation = """
    The city is renowned for its opulent palaces, temples, parks, gardens, tombs, walls and gates. Beijing is one of the most 
   important tourist destinations of the world. In 2018, Beijing was the second highest earning tourist city in the world after Shanghai. 
    """

    [[capitals.questions]]
    question = "what is the capital of Brazil"
    answers = ["Brasillia"]
    alternatives = ["sao Paulo", "Rio de Janeiro", "Manaus", "Belem"]
    hint = "It has a similar name as brazil"
    explanation = """
    The Brasillia city of Brazil is the largest country in South America. Brazil is the home to the second largest river in the world. 
    """

    [[capitals.questions]]
    question = "what is the capital of US"
    answers = ["Washington DC"]
    alternatives = ["New York", "Chicago", "Los Angeles", "Miami"]
    hint = "It grows the most apples in the US."
    explanation = """
    When the washington Monument opened on october9 , 1888, it was the tallest man made structure in the world.
    """

    [[capitals.questions]]
    question = "what is the capital of canada"
    answers = ["Ottawa"]
    alternatives = ["Toronto", "Montreal", "Kingston", "CalGary"]
    hint = "Largest ice skating rink in the world."
    explanation = """
    The name ottawa comes from the Algonquin word adawe which means to trade, so it always been an important business centre.Ottawa is the seventh coldest city in the world.
"""

    [[capitals.questions]]
    question = "what is the capital of New Zealand"
    answers = ["Wellington"]
    alternatives = ["Aukland", "Christchurch", "Dunedin", "Invercagil"]
    hint = "faced one of the worse earthquakes in 2011"
    explanation = """
    Christchurch is located in the south island, christchurch have a lot of green spaces such a lot fo parks and trees. 
    """

    [[capitals.questions]]
    question = "what is the capital of Japan"
    answers = ["Tokyo"]
    alternatives = ["Osaka", "Kyoto", "Kobe", "sendai"]
    hint = "olympic was held there "
    explanation = """
    Tokyo is one of the largest cities in the world and the most popular city in japan also know for holding olympics. 
    """

    [[capitals.questions]]
    question = "what is the capital of Sri lanka"
    answers = ["Colombo"]
    alternatives = ["Osaka", "Kyoto", "Kobe", "sendai"]
    hint = "It starts with a letter c "
    explanation = """
Colombo is the largest city in sri lanka as the population, it is known to be rich in culture , and natural beauty with lot of mountains and green land. 
    """





     

